-- MySQL Script generated by MySQL Workbench
-- Fri Aug  5 11:30:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gunterbr
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gunterbr
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gunterbr` DEFAULT CHARACTER SET utf8 ;
USE `gunterbr` ;

-- -----------------------------------------------------
-- Table `gunterbr`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gunterbr`.`login` (
  `idlogin` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idlogin`, `username`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gunterbr`.`inscricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gunterbr`.`inscricao` (
  `idinscricao` INT NOT NULL AUTO_INCREMENT,
  `nomeCandidato` VARCHAR(45) NOT NULL,
  `contato` INT NULL,
  `evento` VARCHAR(45) NOT NULL,
  `numeroInscricao` INT NOT NULL,
  `deferida` VARCHAR(45) NULL,
  `responsavel` VARCHAR(45) NULL,
  PRIMARY KEY (`idinscricao`, `numeroInscricao`),
  UNIQUE INDEX `numeroInscricao_UNIQUE` (`numeroInscricao` ASC) VISIBLE,
  UNIQUE INDEX `idinscricao_UNIQUE` (`idinscricao` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gunterbr`.`comprovante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gunterbr`.`comprovante` (
  `idcomprovante` INT NOT NULL AUTO_INCREMENT,
  `fieldname` VARCHAR(45) NULL,
  `originalname` VARCHAR(45) NULL,
  `encoding` VARCHAR(45) NULL,
  `mimetype` VARCHAR(45) NULL,
  `destination` VARCHAR(45) NULL,
  `filename` VARCHAR(45) NULL,
  `path` VARCHAR(45) NULL,
  `size` VARCHAR(45) NULL,
  `fk_numeroInscricao` INT NOT NULL,
  PRIMARY KEY (`idcomprovante`),
  INDEX `fk_comprovante_inscricao_idx` (`fk_numeroInscricao` ASC) VISIBLE,
  CONSTRAINT `fk_comprovante_inscricao`
    FOREIGN KEY (`fk_numeroInscricao`)
    REFERENCES `gunterbr`.`inscricao` (`numeroInscricao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
